query FindProducts($first: Int) {
  products(first: $first) {
    edges {
      node {
        title
        id
        description
        media(first: $first) {
          edges {
            node {
              previewImage {
                src
              }
            }
          }
        }
      }
    }
  }
}

query FindShop {
  shop {
    name
  }
}
