query FindProducts($first: Int) {
  products(first: $first) {
    edges {
      node {
        title
        id
        priceRange {
          maxVariantPrice {
            amount
          }
        }
        featuredImage {
          url
        }
      }
    }
  }
}
