query GetProducts($first: Int) {
  products(first: $first) {
    edges {
      node {
        title
        id
        priceRange {
          maxVariantPrice {
            amount
          }
        }
        featuredImage {
          url
        }
      }
    }
  }
}

query FindProduct($id: ID, $first: Int) {
  product(id: $id) {
    id
    title
    featuredImage {
      url
    }
    description
    priceRange {
      maxVariantPrice {
        amount
      }
    }
    variants(first: $first) {
      edges {
        node {
          selectedOptions {
            name
            value
          }
        }
      }
    }
  }
}
